### ISSUE TITLE
bpe_model Issue.

### ISSUE THREAD

**Issue by jamalabdul1** [mnschmit/graformer#1]
I am trying to reproduce this code but while trying it on 'webnlg' data the `Prepare_webnlg.py` throws the following error `TypeError: add_string_to_graph() missing 1 required positional argument: 'bpe_dropout'`

can anyone help me please?

**Comment by mnschmit** [comment]
Hi @jamalabdul1 
Thank you for bringing this to my attention. It was a small problem of the `bpe_dropout` argument not being passed down to all helper functions that expected it. Please pull again and see if my last change solves your issue.
Feel free to reopen if your problem persists.
