### ISSUE TITLE
Equation 7 implementation

### ISSUE THREAD

**Issue by evinpinar** [mnschmit/graformer#2]
Could you point out the line of code where the relative attention summation is implemented (Equation 7)? 
As far as I see, [this](https://github.com/mnschmit/graformer/blob/9e1d38d33b2867364d35a2634e4bc02e3a447d27/src/models/relative_attention.py#L124) part multiplies the relative attention R with query, which is an operation in between Equation 4 and 7. Is it the final implementation that you've used? 
Thanks!

**Comment by mnschmit** [comment]
Hi @evinpinar 
thank you for your question and sorry it took me a while to come back to you!

The relative attention mechanism described in the paper (i.e., the one we conducted our experiments with) is implemented in `relative_attention_scalars.py`. It uses scalar embeddings as opposed to the one you are linking to, which is using full embeddings and therefore needs the matrix multiplication you mention. The sum of Equation 7 is implemented [here](https://github.com/mnschmit/graformer/blob/9e1d38d33b2867364d35a2634e4bc02e3a447d27/src/models/relative_attention_scalars.py#L103). `attn_output_weights` is the left part (cf. [here](https://github.com/mnschmit/graformer/blob/9e1d38d33b2867364d35a2634e4bc02e3a447d27/src/models/relative_attention_scalars.py#L84)) and `pos_emb` is gamma(R). See also lines 88 to 101 for the computation of `pos_emb`: The `scalar_matrix` represents R (can be given as parameter for graphs; if None, a sequence is assumed). `self.pos_embed` is gamma.

I hope this answers your question and I will therefore close the issue. But feel free to reopen if anything is unclear!
